'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id),keys=new Set();
const W=1280,H=780,G=9.8,BASE=11.885,SINGLE=4.115;
let player,opponent,ball,phase,paused,points,games,server,rally,best=0,clock=0,timer=0,buffer=0,swingAnim=0,aiAnim=0,message='',last=0,acc=0,trail=[],reason='',shotSerial=0;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function project(x,y,z=0){const t=(y+15)/30,scale=25+37*t;return{x:640+x*scale,y:156+t*545-z*scale*.9,s:scale};}
function poly(pts,fill,stroke,width=2){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function worldLine(x1,y1,x2,y2,color='#f3f6ee',width=3){let a=project(x1,y1),b=project(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
function announce(s){message=s;$('message').textContent=s}
function displayScore(p,q){if(p>=3&&q>=3)return p===q?'40':p>q?'AD':'40';return ['0','15','30','40'][Math.min(p,3)]}
function ui(){$('you').textContent=displayScore(points[0],points[1]);$('cpu').textContent=displayScore(points[1],points[0]);$('yg').textContent=games[0];$('cg').textContent=games[1];$('state').textContent=paused?'PAUSED':phase==='match'?'MATCH COMPLETE':phase==='serve'?(server===0?'YOUR SERVE':'CPU SERVE'):phase==='point'?'POINT OVER':'LIVE RALLY';$('rally').textContent=`Rally ${rally} · Best ${best}`}
function ready(){player={x:-1.7,y:10,step:0};opponent={x:1.7,y:-10,step:0};ball={x:server?opponent.x:player.x,y:server?-10:10,z:2.2,vx:0,vy:0,vz:0,last:server,bounces:0};trail=[];rally=0;buffer=0;phase='serve';timer=1.2;announce(server?'Opponent serving…':'Press Space or Serve to start.');ui()}
function reset(){points=[0,0];games=[0,0];server=0;paused=false;clock=0;shotSerial=0;swingAnim=aiAnim=0;$('pause').textContent='Pause';ready()}
function strike(who,aim){const destination=who===0?-8.8:9.0;const duration=who===0?1.32:1.58;ball.vx=(aim-ball.x)/duration;ball.vy=(destination-ball.y)/duration;ball.vz=(.5*G*duration*duration-ball.z)/duration;ball.last=who;ball.bounces=0;rally++;best=Math.max(best,rally);shotSerial++;if(who===0)swingAnim=.3;else aiAnim=.3;buffer=0;announce(who===0?'Return sent. Recover for the next ball.':'Incoming! Swing when the ball reaches you.');ui()}
function serve(){phase='rally';ball.x=server?opponent.x:player.x;ball.y=server?-10:10;ball.z=2.3;strike(server,server===0?1.4:-1.8)}
function canHit(){return phase==='rally'&&ball.last===1&&ball.y>0&&Math.hypot(ball.x-player.x,(ball.y-player.y)*.85)<2.15&&ball.z>.12&&ball.z<3.1}
function swing(){if(paused)return;if(phase==='match'){reset();return}if(phase==='serve'&&server===0){serve();return}if(phase!=='rally')return;buffer=.22;swingAnim=.22;if(canHit())returnBall();else announce('Get close to the ball — time your swing.');}
function returnBall(){const aim=keys.has('KeyA')?-3.45:keys.has('KeyD')?3.45:clamp(-opponent.x*.75,-2.4,2.4);strike(0,aim)}
function point(winner,why){if(phase!=='rally')return;points[winner]++;reason=why;phase='point';timer=2;announce(`${winner===0?'Your':'CPU'} point · ${why}`);if(points[winner]>=4&&points[winner]-points[1-winner]>=2){games[winner]++;points=[0,0];server=1-server;announce(`${winner===0?'You win':'CPU wins'} the game!`);if(games[winner]>=2){phase='match';announce(`${winner===0?'You win the match!':'CPU wins the match.'} Press New match to play again.`)}}ui()}
function landing(){let t=(ball.vz+Math.sqrt(ball.vz*ball.vz+2*G*Math.max(0,ball.z)))/G;return{x:ball.x+ball.vx*t,y:ball.y+ball.vy*t}}
function move(p,x,y,speed,dt){let dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy);if(d>.03){const scale=Math.min(1,speed*dt/d);p.x+=dx*scale;p.y+=dy*scale;p.step+=dt*12}else p.step*=.9;}
function step(dt){if(paused)return;clock+=dt;buffer=Math.max(0,buffer-dt);swingAnim=Math.max(0,swingAnim-dt);aiAnim=Math.max(0,aiAnim-dt);if(phase==='match')return;
 const dx=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),dy=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);
 if(dx||dy)move(player,clamp(player.x+dx,-5.8,5.8),clamp(player.y+dy,2,13),7,dt);
 else if($('assist').checked&&phase==='rally'&&ball.last===1){const target=landing();move(player,clamp(target.x,-5.3,5.3),clamp(target.y+.75,6.5,11),6.3,dt)}
 if(phase==='serve'){ball.x=server?opponent.x:player.x;if(server&&(timer-=dt)<=0)serve();return}
 if(phase==='point'){if((timer-=dt)<=0)ready();return}
 const target=landing();move(opponent,ball.last===0?clamp(target.x,-5,5):0,-9.5,4.4,dt);
 const oldY=ball.y;ball.vz-=G*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.z+=ball.vz*dt;
 if(oldY*ball.y<=0&&Math.abs(ball.x)<5.5&&ball.z<.94){point(1-ball.last,'net');return}
 if(ball.z<=0){ball.z=0;const correctSide=ball.last===0?ball.y<0:ball.y>0;if(ball.bounces===0&&(!correctSide||Math.abs(ball.x)>SINGLE||Math.abs(ball.y)>BASE)){point(1-ball.last,'out');return}ball.bounces++;if(ball.bounces>=2){point(ball.last,'second bounce');return}ball.vz=Math.abs(ball.vz)*.72;ball.vx*=.94;ball.vy*=.94;}
 if(buffer>0&&canHit())returnBall();
 if(ball.last===0&&ball.y< -6.5&&Math.hypot(ball.x-opponent.x,(ball.y-opponent.y)*.85)<1.7&&ball.z>.2&&ball.z<2.6){const aim=Math.sin(shotSerial*2.17)*3.5;strike(1,aim)}
 if(Math.abs(ball.y)>17||Math.abs(ball.x)>10)point(ball.bounces?ball.last:1-ball.last,'ball past the baseline');
 trail.push({x:ball.x,y:ball.y,z:ball.z});if(trail.length>12)trail.shift();}
const background=document.createElement('canvas');background.width=W;background.height=H;
function makeBackground(){const c=background.getContext('2d');c.fillStyle='#193449';c.fillRect(0,0,W,H);for(let i=0;i<480;i++){const x=(i*43)%1280,y=8+(i*17)%88;c.fillStyle=['#c7bba6','#78909c','#e7dfcc','#48505c'][i%4];c.beginPath();c.arc(x,y,2.5,0,7);c.fill()}c.fillStyle='#12314a';c.fillRect(0,89,W,70);c.fillStyle='#dbe5e9';c.font='20px Georgia';c.textAlign='center';['BASELINE','TENNIS CLUB','THE OPEN COURT','BASELINE'].forEach((s,i)=>c.fillText(s,160+i*320,127));c.fillStyle='#628c64';c.fillRect(0,158,W,H-158);}
function athlete(p,color,anim,far){let a=project(p.x,p.y),s=a.s/48;ctx.save();ctx.translate(a.x,a.y);ctx.scale(s,s);ctx.fillStyle='#18332944';ctx.beginPath();ctx.ellipse(0,0,20,6,0,0,7);ctx.fill();const gait=Math.sin(p.step)*8;ctx.strokeStyle='#523c32';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-8,-40);ctx.lineTo(-11-gait,-20);ctx.lineTo(-12-gait,0);ctx.moveTo(8,-40);ctx.lineTo(11+gait,-20);ctx.lineTo(12+gait,0);ctx.stroke();ctx.strokeStyle='#dde5da';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-17-gait,0);ctx.lineTo(-7-gait,0);ctx.moveTo(7+gait,0);ctx.lineTo(17+gait,0);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-13,-73);ctx.lineTo(12,-73);ctx.lineTo(17,-36);ctx.lineTo(-17,-36);ctx.closePath();ctx.fill();ctx.fillStyle='#684939';ctx.beginPath();ctx.arc(0,-84,10,0,7);ctx.fill();ctx.fillStyle='#211e26';ctx.beginPath();ctx.arc(-1,-89,10,Math.PI,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-6,-95,6,0,7);ctx.fill();const reach=anim>0?Math.sin(anim/.3*Math.PI)*28:0;ctx.strokeStyle='#684939';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-11,-67);ctx.lineTo(-22,-49);ctx.moveTo(11,-67);ctx.lineTo(25+reach,-54-reach*.35);ctx.stroke();ctx.strokeStyle='#d8dfae';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(25+reach,-54-reach*.35);ctx.lineTo(38+reach,-60-reach*.35);ctx.stroke();ctx.save();ctx.translate(48+reach,-64-reach*.35);ctx.rotate(-.45);ctx.beginPath();ctx.ellipse(0,0,12,17,0,0,7);ctx.stroke();ctx.strokeStyle='#eef4d777';ctx.lineWidth=1;for(let i=-6;i<=6;i+=4){ctx.beginPath();ctx.moveTo(i,-12);ctx.lineTo(i,12);ctx.stroke()}ctx.restore();ctx.restore();}
function drawNet(){const a=project(-5.5,0),b=project(5.5,0),topa=project(-5.5,0,1.05),topb=project(5.5,0,1.05);poly([a,b,topb,topa],'#162b3c88');for(let x=-5.5;x<=5.5;x+=.2){let p=project(x,0),q=project(x,0,1);ctx.strokeStyle='#d1d9d54d';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}for(let z=.2;z<1;z+=.2){let p=project(-5.5,0,z),q=project(5.5,0,z);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}ctx.strokeStyle='#f2f3e8';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(topa.x,topa.y);ctx.quadraticCurveTo(640,topa.y+7,topb.x,topb.y);ctx.stroke()}
function draw(){ctx.drawImage(background,0,0);poly([project(-5.485,-BASE),project(5.485,-BASE),project(5.485,BASE),project(-5.485,BASE)],'#49669c','#f2f5eb',3);for(const x of [-SINGLE,SINGLE])worldLine(x,-BASE,x,BASE);worldLine(-SINGLE,-6.4,SINGLE,-6.4);worldLine(-SINGLE,6.4,SINGLE,6.4);worldLine(0,-6.4,0,6.4);worldLine(0,-BASE,0,-BASE+.4);worldLine(0,BASE,0,BASE-.4);
 athlete(opponent,'#929684',aiAnim,true);drawNet();
 if(phase==='rally'){const l=landing(),p=project(l.x,l.y);ctx.strokeStyle='#ddeb78aa';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,12,5,0,0,7);ctx.stroke()}
 const p=project(player.x,player.y);ctx.strokeStyle=canHit()?'#e7fb9a':'#eef4d950';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.ellipse(p.x,p.y,55,15,0,0,7);ctx.stroke();ctx.setLineDash([]);athlete(player,'#a347a8',swingAnim,false);
 if(phase==='rally'||phase==='serve'){const shadow=project(ball.x,ball.y);ctx.fillStyle='#18332966';ctx.beginPath();ctx.ellipse(shadow.x,shadow.y,6,3,0,0,7);ctx.fill();for(let i=0;i<trail.length;i++){let a=project(trail[i].x,trail[i].y,trail[i].z);ctx.fillStyle=`rgba(231,247,118,${i/trail.length*.3})`;ctx.beginPath();ctx.arc(a.x,a.y,2,0,7);ctx.fill()}const a=project(ball.x,ball.y,ball.z);ctx.fillStyle='#e5f65f';ctx.strokeStyle='#fcffe3';ctx.lineWidth=1;ctx.beginPath();ctx.arc(a.x,a.y,Math.max(3,a.s*.09),0,7);ctx.fill();ctx.stroke();}
 if(paused||phase==='match'||phase==='point'){ctx.fillStyle='#0c1c2788';ctx.fillRect(0,320,W,100);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='28px Georgia';ctx.fillText(paused?'Paused':phase==='match'?(games[0]>games[1]?'You win the match':'Match complete'):(reason==='net'?'Into the net':message),640,378)}
 ctx.fillStyle='#ffffffbb';ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText('YOU / NEAR COURT',30,750);ctx.textAlign='right';ctx.fillText(canHit()?'SWING NOW':keys.has('KeyA')?'AIM: LEFT':keys.has('KeyD')?'AIM: RIGHT':'AIM: OPEN COURT',1250,750);}
function pause(){paused=!paused;keys.clear();$('pause').textContent=paused?'Resume':'Pause';ui()}
$('swing').onclick=swing;$('reset').onclick=reset;$('pause').onclick=pause;
window.addEventListener('keydown',e=>{if(e.target.matches('input,video')||e.target.matches('button')&&e.code==='Space')return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space')swing();if(e.code==='KeyP')pause();if(e.code==='KeyR')reset()});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(!paused&&phase==='rally')pause()});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key))}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();swing()});
makeBackground();reset();function frame(t){acc+=Math.min((t-last)/1000,.08);last=t;while(acc>=1/120){step(1/120);acc-=1/120}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.tennis={snapshot:()=>JSON.parse(JSON.stringify({phase,paused,points,games,server,rally,best,player,opponent,ball,message})),step,reset,swing,canHit};
