'use strict';
const {Engine,Bodies,Body,Composite,Events,Vector}=Matter;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1280,H=720,GROUND=640,ANCHOR={x:185,y:535},MAX_PULL=104,LAUNCH_SCALE=.20;
let engine,blocks=[],birds=[],target,bird,phase='ready',paused=false,dragging=false,pointerId=null,pull={...ANCHOR},score=0,used=0,flightTime=0,time=0,targetGone=false,victoryDelay=0,particles=[],popups=[],trail=[],pending=new Set(),settling=false,impacts=0;
const $=id=>document.getElementById(id);
function addBox(x,y,w,h,kind='wood',fixed=false){const b=Bodies.rectangle(x,y,w,h,{isStatic:fixed,density:kind==='glass'?.0011:.002,friction:.65,frictionStatic:1,restitution:.035,frictionAir:.002,label:kind});b.art={kind,w,h,hp:kind==='glass'?19:55,maxHp:kind==='glass'?19:55,seed:x+y,original:{x,y}};Composite.add(engine.world,b);if(!fixed)blocks.push(b);return b;}
function newBird(){bird=Bodies.circle(ANCHOR.x,ANCHOR.y,18,{density:.009,friction:.6,restitution:.18,frictionAir:0,label:'bird'});Body.setStatic(bird,true);birds.push(bird);Composite.add(engine.world,bird);pull={...ANCHOR};phase='ready';flightTime=0;trail=[];dragging=false;}
function reset(){if(engine)Engine.clear(engine);engine=Engine.create({enableSleeping:true,positionIterations:10,velocityIterations:10});engine.gravity.y=.7;engine.timing.timeScale=.7;blocks=[];birds=[];score=0;used=0;time=0;targetGone=false;victoryDelay=0;particles=[];popups=[];trail=[];pending=new Set();paused=false;dragging=false;pointerId=null;impacts=0;
 addBox(640,670,1700,60,'ground',true);addBox(940,591,270,14,'platform',true);
 addBox(884,522,14,124);addBox(996,522,14,124);addBox(940,453,140,14);
 addBox(910,384,14,124);addBox(970,384,14,124);addBox(940,315,74,14);addBox(940,291,14,34);
 addBox(940,439,34,14);addBox(940,580,68,8);addBox(917,552,12,48,'glass');addBox(963,552,12,48,'glass');addBox(940,521,68,14);
 target=Bodies.circle(940,413,18,{density:.002,friction:.7,restitution:.1,label:'target'});target.hp=18;Composite.add(engine.world,target);
 Events.on(engine,'collisionStart',event=>{if(settling||used===0)return;for(const pair of event.pairs){const a=pair.bodyA,b=pair.bodyB;const va=a._impactVelocity||a.velocity,vb=b._impactVelocity||b.velocity;const speed=Math.hypot(va.x-vb.x,va.y-vb.y);if(speed<2.6)continue;impacts++;
 for(const body of [a,b]){if(body.label==='target'&&!targetGone){body.hp-=(speed-2)*9;if(body.hp<=0)pending.add(body);}if(body.art&&!body.isStatic){body.art.hp-=(speed-2.6)*9;if(body.art.hp<=0)pending.add(body);}}}});
 settling=true;for(let i=0;i<220;i++)Engine.update(engine,1000/120);settling=false;newBird();$('overlay').hidden=true;$('pause').textContent='Pause';syncUI();draw();}
function burst(x,y,color,count=16){for(let i=0;i<count;i++){const a=i*2.39996;particles.push({x,y,vx:Math.cos(a)*(40+(i%5)*30),vy:Math.sin(a)*(40+(i%7)*25)-70,life:.65+(i%4)*.15,max:1.1,size:2+i%5,color,rotation:a});}}
function destroy(b){if(b===target){if(targetGone)return;targetGone=true;score+=5000;burst(b.position.x,b.position.y,'#89b744',26);popups.push({x:b.position.x,y:b.position.y-25,text:'+5,000',life:1.8,color:'#547d25'});victoryDelay=2.5;}else{const i=blocks.indexOf(b);if(i<0)return;blocks.splice(i,1);score+=b.art.kind==='glass'?300:150;burst(b.position.x,b.position.y,b.art.kind==='glass'?'#8dd4e3':'#c58b42');popups.push({x:b.position.x,y:b.position.y,text:b.art.kind==='glass'?'+300':'+150',life:1,color:'#8f6e36'});}Composite.remove(engine.world,b);}
function setPull(x,y){let dx=x-ANCHOR.x,dy=y-ANCHOR.y;const len=Math.hypot(dx,dy);if(len>MAX_PULL){dx*=MAX_PULL/len;dy*=MAX_PULL/len;}pull={x:ANCHOR.x+dx,y:ANCHOR.y+dy};Body.setPosition(bird,pull);}
function launch(){if(paused||!['ready','aiming'].includes(phase))return;const dx=ANCHOR.x-pull.x,dy=ANCHOR.y-pull.y;if(Math.hypot(dx,dy)<8){setPull(ANCHOR.x,ANCHOR.y);phase='ready';dragging=false;return;}Body.setStatic(bird,false);Body.setVelocity(bird,{x:dx*LAUNCH_SCALE,y:dy*LAUNCH_SCALE});Body.setAngularVelocity(bird,-.035);phase='flying';used++;flightTime=0;dragging=false;pointerId=null;syncUI();}
function settingsShot(){if(paused||phase!=='ready')return;const a=Number($('angle').value)*Math.PI/180,r=MAX_PULL*Number($('power').value)/100;setPull(ANCHOR.x-Math.cos(a)*r,ANCHOR.y+Math.sin(a)*r);launch();}
function nextBird(){if(paused||phase!=='flying'||flightTime<1||targetGone)return;if(used<3)newBird();else if(flightTime>7)finish(false);syncUI();}
function finish(win){phase=win?'won':'lost';$('resultTitle').textContent=win?'A beautiful chain reaction.':'One more angle?';$('resultText').textContent=win?`Target cleared. ${score.toLocaleString()} points from ${used} ${used===1?'bird':'birds'}.`:'The target is still standing. Reset the tower and try a different pull.';$('again').textContent=win?'Play again ↗':'Try again ↗';$('overlay').hidden=false;syncUI();}
function step(dt){if(paused)return;time+=dt;
 if(used>0){if(phase==='flying')flightTime+=dt;for(const b of Composite.allBodies(engine.world))b._impactVelocity=Body.getVelocity(b);Engine.update(engine,dt*1000);for(const b of pending)destroy(b);pending.clear();if(!targetGone&&(target.position.y>GROUND+30||target.position.x>W+100||target.position.x< -100))destroy(target);
 if(phase==='flying'){if(Math.floor(flightTime*20)>trail.length&&trail.length<200)trail.push({...bird.position});if(!targetGone&&(flightTime>9||(flightTime>2&&(bird.position.x>W+100||bird.position.x< -100)))){if(used<3)newBird();else finish(false);}}
 if(targetGone&&!['won','lost'].includes(phase)){victoryDelay-=dt;if(victoryDelay<=0)finish(true);}}
 for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.rotation+=dt*3;}particles=particles.filter(p=>p.life>0);for(const p of popups){p.life-=dt;p.y-=dt*25;}popups=popups.filter(p=>p.life>0);syncUI();}
function syncUI(){if(phase==='won')$('resultText').textContent=`Target cleared. ${score.toLocaleString()} points from ${used} ${used===1?'bird':'birds'}.`;$('score').textContent=String(score).padStart(5,'0');$('shots').textContent=`${3-used} ${3-used===1?'BIRD':'BIRDS'} LEFT`;$('used').textContent=`${used} / 3`;$('targets').textContent=targetGone?'0 / 1':'1 / 1';$('message').textContent=paused?'PAUSED':phase==='ready'?'PULL BACK & RELEASE':phase==='aiming'?'RELEASE TO LAUNCH':phase==='won'?'TARGET CLEARED':phase==='lost'?'OUT OF BIRDS':targetGone?'WATCH IT TUMBLE':flightTime>1?'WATCH THE IMPACT · NEXT BIRD AVAILABLE':'IN FLIGHT';$('next').disabled=paused||phase!=='flying'||flightTime<1||targetGone||used>=3;$('launch').disabled=paused||phase!=='ready';$('demo').disabled=paused||phase!=='ready';}
function path(points,fill,stroke,width=2){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
const backdrop=document.createElement('canvas');backdrop.width=W;backdrop.height=H;
function makeBackdrop(){const c=backdrop.getContext('2d');const sky=c.createLinearGradient(0,0,0,640);sky.addColorStop(0,'#d9edf0');sky.addColorStop(.6,'#eef6ed');sky.addColorStop(1,'#f8f6e5');c.fillStyle=sky;c.fillRect(0,0,W,H);
 function hill(y,color,phase){c.beginPath();c.moveTo(0,H);for(let x=0;x<=W+20;x+=20)c.lineTo(x,y+Math.sin(x/210+phase)*25+Math.sin(x/115+phase)*12);c.lineTo(W,H);c.closePath();c.fillStyle=color;c.fill();}hill(465,'#d5dfdf',2);hill(550,'#c6d6c4',4);
 c.strokeStyle='#fff9';c.lineWidth=13;c.lineCap='round';c.beginPath();c.moveTo(-30,155);c.bezierCurveTo(180,85,210,185,330,142);c.bezierCurveTo(530,63,595,156,758,125);c.bezierCurveTo(960,58,1100,130,1310,78);c.stroke();
 for(const [x,y,s] of [[325,602,1.1],[1120,603,1.45],[670,601,.55],[49,607,.7],[760,610,.65]]){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#b6c9cc';c.fillRect(-18,-200,36,200);c.strokeStyle='#b6c9cc';c.lineWidth=15;c.beginPath();c.moveTo(0,-130);c.quadraticCurveTo(-70,-90,-78,-175);c.moveTo(0,-155);c.quadraticCurveTo(55,-116,63,-199);c.stroke();for(const [lx,ly,r] of [[-78,-193,-.3],[62,-219,.2],[0,-244,0]]){c.save();c.translate(lx,ly);c.rotate(r);c.beginPath();c.moveTo(0,25);c.bezierCurveTo(-52,-15,-32,-35,-35,-48);c.lineTo(-18,-36);c.bezierCurveTo(-25,-89,-5,-112,0,-110);c.bezierCurveTo(12,-92,20,-63,18,-44);c.lineTo(33,-57);c.bezierCurveTo(41,-20,20,11,0,25);c.fill();c.restore();}c.restore();}
 c.fillStyle='#718c48';c.fillRect(0,638,W,82);c.fillStyle='#495f38';c.fillRect(0,657,W,63);for(let i=0;i<150;i++){const x=i*9.3,ht=12+(Math.sin(i*17.3)+1)*14;c.strokeStyle=i%3?'#718c49':'#8fa64b';c.lineWidth=3;c.beginPath();c.moveTo(x,644);c.quadraticCurveTo(x-6,637-ht/2,x+(i%2?7:-9),637-ht);c.stroke();}c.fillStyle='#aac463';c.fillRect(0,638,W,7);for(let i=0;i<55;i++){c.fillStyle=i%2?'#6d8047':'#859956';c.fillRect(i*24+7,666+(i*13)%45,4+(i%4)*3,3);} }
function drawWood(b){const {w,h,kind,hp,maxHp}=b.art;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);if(kind==='glass'){ctx.fillStyle='#8ad4e5a6';ctx.strokeStyle='#60adbc';ctx.lineWidth=2;ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeRect(-w/2,-h/2,w,h);ctx.strokeStyle='#f4ffffc9';ctx.beginPath();ctx.moveTo(-w/2+3,h/2-5);ctx.lineTo(w/2-3,-h/2+5);ctx.stroke();}else{const g=ctx.createLinearGradient(-w/2,-h/2,w/2,h/2);g.addColorStop(0,'#e3af64');g.addColorStop(.4,'#c89047');g.addColorStop(1,'#aa6d34');ctx.fillStyle=g;ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeStyle='#855b31';ctx.lineWidth=2;ctx.strokeRect(-w/2,-h/2,w,h);ctx.strokeStyle='#f4ce86';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-w/2+3,h/2-3);ctx.lineTo(-w/2+3,-h/2+3);ctx.lineTo(w/2-3,-h/2+3);ctx.stroke();ctx.strokeStyle='#9f6c3577';ctx.lineWidth=1;for(let i=0;i<3;i++){ctx.beginPath();if(w>h){ctx.moveTo(-w/2+8,-h/2+4+i*3);ctx.bezierCurveTo(-w/4,3,w/8,-3,w/2-8,-h/2+4+i*3);}else{ctx.moveTo(-w/2+4+i*3,-h/2+8);ctx.bezierCurveTo(2,-h/4,-3,h/8,-w/2+4+i*3,h/2-8);}ctx.stroke();}}if(hp<maxHp*.65){ctx.strokeStyle=kind==='glass'?'#fff':'#79512f';ctx.beginPath();ctx.moveTo(-w*.3,-h*.25);ctx.lineTo(0,0);ctx.lineTo(-w*.2,h*.18);ctx.lineTo(w*.3,h*.3);ctx.stroke();}ctx.restore();}
function drawBird(x,y,angle=0,scale=1){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(scale,scale);path([[-15,5],[-27,1],[-23,10],[-14,12]],'#503b31');path([[-8,-14],[-12,-26],[-2,-21],[2,-26],[9,-15]],'#b84031','#87362b');ellipse(0,0,19,18,'#c64b3a');ctx.strokeStyle='#8d3a2d';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,19,18,0,0,Math.PI*2);ctx.stroke();ellipse(2,11,13,7,'#f4e8d4');ellipse(7,-3,6,7,'#fff9e9');ellipse(16,-2,4.5,6,'#fff9e9');ellipse(9,-2,2,3,'#343b31');ellipse(17,-1,1.8,2.5,'#343b31');path([[9,5],[29,5],[15,12]],'#e9b143','#8c6034',1.5);ctx.strokeStyle='#54372c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-1,-12);ctx.lineTo(12,-8);ctx.lineTo(20,-11);ctx.stroke();ctx.restore();}
function drawTarget(){if(targetGone)return;ctx.save();ctx.translate(target.position.x,target.position.y);ctx.rotate(target.angle);ellipse(-10,-16,5,7,'#82ac4c');ellipse(9,-17,5,7,'#82ac4c');ellipse(0,0,20,18,'#88b651');ctx.strokeStyle='#587a38';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,20,18,0,0,Math.PI*2);ctx.stroke();ellipse(-9,-4,5,6,'#fffce9');ellipse(10,-4,5,6,'#fffce9');ellipse(-8,-3,1.8,2.5,'#354e30');ellipse(9,-3,1.8,2.5,'#354e30');ellipse(1,6,11,8,'#b5ce6a');ellipse(-3,6,2,3,'#5c803c');ellipse(5,6,2,3,'#5c803c');ctx.restore();}
function sling(back){ctx.lineCap='round';if(back){ctx.strokeStyle='#654a30';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(185,639);ctx.lineTo(186,582);ctx.quadraticCurveTo(166,565,169,520);ctx.stroke();ctx.strokeStyle='#bd965e';ctx.lineWidth=10;ctx.stroke();}else{ctx.strokeStyle='#654a30';ctx.lineWidth=17;ctx.beginPath();ctx.moveTo(186,583);ctx.quadraticCurveTo(207,564,207,523);ctx.stroke();ctx.strokeStyle='#c69c62';ctx.lineWidth=10;ctx.stroke();}const end=phase==='ready'||phase==='aiming'?pull:ANCHOR;ctx.strokeStyle='#654135';ctx.lineWidth=back?6:5;ctx.beginPath();ctx.moveTo(back?169:207,530);ctx.lineTo(end.x,end.y+3);ctx.stroke();}
function trajectory(){if(!['ready','aiming'].includes(phase))return;const a=Number($('angle').value)*Math.PI/180,r=MAX_PULL*Number($('power').value)/100;const start=phase==='aiming'?pull:{x:ANCHOR.x-Math.cos(a)*r,y:ANCHOR.y+Math.sin(a)*r};const vx=(ANCHOR.x-start.x)*LAUNCH_SCALE,vy=(ANCHOR.y-start.y)*LAUNCH_SCALE;for(let i=1;i<=26;i++){const t=i*2;const x=start.x+vx*t,y=start.y+vy*t+.5*.7*(1000/60)**2*.001*t*t;if(y>GROUND||x>W)break;ellipse(x,y,2.2,2.2,phase==='aiming'?'#f8faf1':'#76927c70');}}
function draw(){ctx.clearRect(0,0,W,H);ctx.drawImage(backdrop,0,0);ellipse(940,640,145,8,'#3f583222');ctx.strokeStyle='#84653f';ctx.lineWidth=7;for(const x of [815,885,955,1065]){ctx.beginPath();ctx.moveTo(x,638);ctx.lineTo(x,598);ctx.stroke();}ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(816,633);ctx.lineTo(883,600);ctx.moveTo(886,633);ctx.lineTo(953,600);ctx.moveTo(957,633);ctx.lineTo(1063,600);ctx.stroke();drawWood({position:{x:940,y:591},angle:0,art:{w:270,h:14,kind:'wood',hp:1,maxHp:1}});
 for(let i=0;i<Math.max(0,3-used-(['ready','aiming'].includes(phase)?1:0));i++)drawBird(84-i*48,621,0,.8);sling(true);trajectory();for(let i=0;i<trail.length;i+=3){const p=trail[i];ellipse(p.x,p.y,2,2,'#fff9');}for(const b of blocks)drawWood(b);drawTarget();for(const b of birds){if(b.position.y<H+50&&b.position.x<W+50)drawBird(b.position.x,b.position.y,b.angle);}sling(false);
 for(const p of particles){ctx.save();ctx.globalAlpha=Math.min(1,p.life/.35);ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.fillStyle=p.color;ctx.fillRect(-p.size,-p.size/2,p.size*2,p.size);ctx.restore();}for(const p of popups){ctx.save();ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.font='bold 24px Georgia';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y);ctx.restore();}}
function localPoint(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('pointerdown',e=>{if(phase!=='ready'||paused||pointerId!==null)return;const p=localPoint(e);if(Math.hypot(p.x-bird.position.x,p.y-bird.position.y)>65)return;e.preventDefault();pointerId=e.pointerId;canvas.setPointerCapture(e.pointerId);dragging=true;phase='aiming';canvas.focus();setPull(p.x,p.y);});
canvas.addEventListener('pointermove',e=>{if(!dragging||e.pointerId!==pointerId||paused)return;const p=localPoint(e);setPull(p.x,p.y);});canvas.addEventListener('pointerup',e=>{if(dragging&&e.pointerId===pointerId)launch();});
function cancelDrag(){if(dragging){dragging=false;pointerId=null;setPull(ANCHOR.x,ANCHOR.y);phase='ready';}}
canvas.addEventListener('pointercancel',cancelDrag);canvas.addEventListener('lostpointercapture',cancelDrag);
function pause(){cancelDrag();paused=!paused;$('pause').textContent=paused?'Resume':'Pause';syncUI();}
$('pause').onclick=pause;$('restart').onclick=reset;$('again').onclick=reset;$('next').onclick=nextBird;$('launch').onclick=settingsShot;$('demo').onclick=()=>{if(phase==='ready'&&!paused){setPull(ANCHOR.x-86,ANCHOR.y+41);launch();}};
for(const id of ['angle','power'])$(id).addEventListener('input',()=>{$(id+'Value').textContent=$(id).value+(id==='angle'?'°':'%');});window.addEventListener('keydown',e=>{if(e.target.matches('input,video'))return;if(e.code==='Space'&&e.target.matches('button,summary,a'))return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)pause();}if(e.key.toLowerCase()==='r')reset();if(e.key.toLowerCase()==='n')nextBird();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused)pause();});
makeBackdrop();reset();let last=0,acc=0;function frame(t){acc+=Math.min((t-last)/1000,.08);last=t;while(acc>=1/120){step(1/120);acc-=1/120;}draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.reconstruction={snapshot:()=>({phase,paused,score,used,targetGone,blocks:blocks.length,impacts,bird:{x:bird.position.x,y:bird.position.y,vx:Body.getVelocity(bird).x,vy:Body.getVelocity(bird).y},target:{x:target.position.x,y:target.position.y},flightTime}),settings:{width:W,height:H,anchor:ANCHOR,maxPull:MAX_PULL}};
