'use strict';
(()=>{
 const KEY='week2-meeting-notes-v1',contexts=[{id:'overview',label:'General / meeting notes'}];
 for(const el of document.querySelectorAll('section[id],article.astra-case[id]')){const h=el.querySelector('h2,h3');if(h)contexts.push({id:el.id,label:h.textContent.trim()});}
 for(const video of document.querySelectorAll('.wrap figure video')){const figure=video.closest('figure'),filename=video.getAttribute('src').split('/').pop();figure.id=figure.id||'note-video-'+filename.replace(/[^a-z0-9_-]/gi,'-');const cap=figure.querySelector('.cap-title');contexts.push({id:figure.id,label:'Video: '+(cap?cap.textContent.trim():filename)+' / '+filename});}
 const button=document.createElement('button');button.className='notes-toggle';button.type='button';button.textContent='+';button.title='Add a note';button.setAttribute('aria-label','Add a note');button.setAttribute('aria-haspopup','dialog');document.body.appendChild(button);
 const dialog=document.createElement('dialog');dialog.className='notes-composer';dialog.id='meeting-notes';dialog.setAttribute('aria-labelledby','notes-title');dialog.innerHTML=`<div class="notes-head"><h2 id="notes-title">Add a note</h2><button type="button" class="notes-close" aria-label="Close note editor">×</button></div><div class="notes-content"><p class="notes-local">Saved only in this browser. Your note stays beside its section.</p><form id="notes-form"><label for="notes-context">Which part?</label><select id="notes-context"></select><blockquote class="notes-quote" hidden></blockquote><label for="notes-text">Note</label><textarea id="notes-text" maxlength="20000" placeholder="Write a question, idea, or next step…"></textarea><div class="notes-actions"><button class="notes-btn primary" id="notes-save" type="submit" disabled>Place note</button><button class="notes-btn" id="notes-cancel" type="button">Cancel</button></div></form><div class="notes-export"><button id="notes-md" type="button">Export Markdown</button><button id="notes-json" type="button">Export JSON</button></div></div>`;document.body.appendChild(dialog);
 const rail=document.createElement('div');rail.className='notes-rail';rail.setAttribute('aria-label','Section notes');document.body.appendChild(rail);
 const toast=document.createElement('div');toast.className='notes-toast';toast.hidden=true;toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');const toastText=document.createElement('span'),undoButton=document.createElement('button');undoButton.type='button';undoButton.textContent='Undo';undoButton.hidden=true;toast.append(toastText,undoButton);document.body.appendChild(toast);
 const find=s=>dialog.querySelector(s),text=find('#notes-text'),context=find('#notes-context'),label=id=>contexts.find(c=>c.id===id)?.label||id;
 for(const c of contexts){const o=document.createElement('option');o.value=c.id;o.textContent=c.label;context.appendChild(o);}
 let notes=[],editing=null,quote='',undo=null,groups=[],timer,storageError=false,scheduled=false;
 function message(value,error=false,offerUndo=false){clearTimeout(timer);toast.hidden=false;toast.dataset.error=String(error);toastText.textContent=value;undoButton.hidden=!offerUndo;if(!error&&!offerUndo)timer=setTimeout(()=>toast.hidden=true,3500);}
 function persist(){try{localStorage.setItem(KEY,JSON.stringify({version:1,notes,draft:{text:text.value,context:context.value,quote,editing}}));storageError=false;return true;}catch{storageError=true;message('Storage unavailable. Notes are only in memory; export before closing.',true);return false;}}
 function valid(n){return n&&typeof n.id==='string'&&typeof n.text==='string'&&typeof n.context==='string'&&typeof n.created==='string';}
 function read(){try{const raw=localStorage.getItem(KEY);if(!raw)return;const d=JSON.parse(raw);if(d.version!==1||!Array.isArray(d.notes)||!d.notes.every(valid))throw Error('Invalid notes');notes=d.notes;if(d.draft){text.value=typeof d.draft.text==='string'?d.draft.text:'';context.value=contexts.some(c=>c.id===d.draft.context)?d.draft.context:'overview';quote=typeof d.draft.quote==='string'?d.draft.quote:'';editing=notes.some(n=>n.id===d.draft.editing)?d.draft.editing:null;}}catch{storageError=true;message('Saved notes could not be read. You can export notes from this session.',true);}}
 function renderForm(){find('#notes-save').disabled=!text.value.trim();find('#notes-save').textContent=editing?'Save changes':'Place note';find('#notes-title').textContent=editing?'Edit note':'Add a note';find('.notes-quote').hidden=!quote;find('.notes-quote').textContent=quote;find('#notes-md').disabled=!notes.length;find('#notes-json').disabled=!notes.length;}
 function clearForm(){text.value='';quote='';editing=null;renderForm();}
 function open(){renderForm();dialog.showModal();context.focus();}
 function close(){dialog.close();button.focus();}
 function anchor(id){const el=document.getElementById(id);if(!el)return document.querySelector('.wrap>header');return el.querySelector('.sec-head,.astra-case-head')||el;}
 function layout(){scheduled=false;const wide=innerWidth>=1100;document.body.classList.toggle('has-margin-notes',wide&&notes.length>0);
  if(wide){for(const g of groups){g.el.classList.remove('notes-inline');if(g.el.parentNode!==rail)rail.appendChild(g.el);}const sorted=groups.map(g=>({...g,y:anchor(g.id).getBoundingClientRect().top+scrollY})).sort((a,b)=>a.y-b.y);let end=0;for(const g of sorted){const y=Math.max(g.y,end);g.el.style.top=y+'px';end=y+g.el.getBoundingClientRect().height+12;}rail.style.height=end?end+'px':'0px';}
  else{rail.style.height='0px';for(const g of groups){g.el.classList.add('notes-inline');g.el.style.top='';const target=anchor(g.id);if(target.nextElementSibling!==g.el)target.insertAdjacentElement('afterend',g.el);}}
 }
 function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(layout);}}
 function render(){for(const g of groups)g.el.remove();groups=[];const map=new Map();for(const n of notes){const id=contexts.some(c=>c.id===n.context)?n.context:'overview';if(!map.has(id)){const el=document.createElement('div');el.className='notes-group';el.dataset.context=id;map.set(id,el);groups.push({id,el});rail.appendChild(el);}const card=document.createElement('article');card.className='note-card';card.dataset.noteId=n.id;const link=document.createElement('button');link.type='button';link.className='note-context';link.textContent=label(n.context);link.onclick=()=>anchor(id).scrollIntoView({block:'start'});card.appendChild(link);
   if(n.quote){const q=document.createElement('blockquote');q.className='notes-quote';q.textContent=n.quote;card.appendChild(q);}const body=document.createElement('p');body.className='note-text';body.textContent=n.text;card.appendChild(body);const tools=document.createElement('div');tools.className='note-tools';const date=document.createElement('span');date.className='note-date';date.textContent=new Date(n.updated||n.created).toLocaleDateString();tools.appendChild(date);const actions=document.createElement('div');actions.className='notes-actions';
   for(const [name,fn] of [['Edit',()=>{editing=n.id;text.value=n.text;context.value=id;quote=n.quote||'';persist();open();text.focus();}],['Delete',()=>{undo={note:n,index:notes.indexOf(n)};notes=notes.filter(x=>x.id!==n.id);if(editing===n.id)clearForm();const saved=persist();render();message(saved?'Note deleted.':'Note deleted in memory; browser storage is unavailable.',!saved,true);}]]){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=fn;actions.appendChild(b);}tools.appendChild(actions);card.appendChild(tools);map.get(id).appendChild(card);
  }renderForm();layout();}
 button.onclick=open;find('.notes-close').onclick=close;find('#notes-cancel').onclick=()=>{clearForm();persist();close();};dialog.addEventListener('cancel',()=>{persist();});
 text.oninput=()=>{renderForm();persist();};context.onchange=()=>persist();find('#notes-form').onsubmit=e=>{e.preventDefault();if(!text.value.trim())return;const now=new Date().toISOString(),id=context.value;if(editing){const n=notes.find(n=>n.id===editing);if(n)Object.assign(n,{context:id,text:text.value.trim(),quote,updated:now});}else notes.push({id:globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),context:id,text:text.value.trim(),quote,created:now,updated:now});clearForm();const saved=persist();render();close();requestAnimationFrame(()=>{const group=groups.find(g=>g.id===id);if(group)group.el.scrollIntoView({block:'nearest'});});if(saved)message('Note placed beside its section.');};
 undoButton.onclick=()=>{if(!undo)return;notes.splice(Math.min(undo.index,notes.length),0,undo.note);undo=null;const saved=persist();render();if(saved)message('Note restored.');else undoButton.hidden=true;};
 function download(format){const output={version:1,page:document.title,exportedAt:new Date().toISOString(),notes:notes.map(n=>({...n,section:label(n.context)}))};const content=format==='json'?JSON.stringify(output,null,2):`# Meeting notes — ${document.title}\n\nExported: ${output.exportedAt}\n\n`+notes.map(n=>`## ${label(n.context)}\n\n${n.quote?n.quote.split('\n').map(l=>'> '+l).join('\n')+'\n\n':''}${n.text}\n`).join('\n---\n\n');const url=URL.createObjectURL(new Blob([content],{type:format==='json'?'application/json':'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`week2-meeting-notes-${new Date().toISOString().slice(0,10)}.${format==='json'?'json':'md'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 find('#notes-md').onclick=()=>download('md');find('#notes-json').onclick=()=>download('json');read();render();window.addEventListener('resize',schedule);new ResizeObserver(schedule).observe(document.querySelector('.wrap'));if(document.fonts)document.fonts.ready.then(schedule);
})();
